import * as Localization from 'expo-localization';
import en from './locales/en.json';import es from './locales/es.json';import vi from './locales/vi.json';import fr from './locales/fr.json';import de from './locales/de.json';import zh from './locales/zh-Hans.json';import names from './data/hobby_translations.json';import firstEn from './data/first_projects.en.json';import firstEs from './data/first_projects.es.json';import firstVi from './data/first_projects.vi.json';import firstFr from './data/first_projects.fr.json';import firstDe from './data/first_projects.de.json';import firstZh from './data/first_projects.zh-Hans.json';import {LocaleCode} from './types';
const dict:Record<LocaleCode,any>={en,es,vi,fr,de,'zh-Hans':zh};const firstProjects:Record<LocaleCode,any>={en:firstEn,es:firstEs,vi:firstVi,fr:firstFr,de:firstDe,'zh-Hans':firstZh};export const locales:LocaleCode[]=['en','es','vi','fr','de','zh-Hans'];let activeLocale:LocaleCode='en';
export function deviceLocale():LocaleCode{const x=Localization.getLocales()[0],tag=x?.languageTag?.toLowerCase()||'',lang=x?.languageCode||'en';if(tag.startsWith('zh-hans')||(lang==='zh'&&!tag.includes('hant')))return'zh-Hans';return locales.includes(lang as LocaleCode)?lang as LocaleCode:'en'}
const path=(o:any,k:string)=>k.split('.').reduce((a,p)=>a?.[p],o);
export function tr(l:LocaleCode,k:string,p:Record<string,string|number>={}){activeLocale=l;let v=path(dict[l],k);if(typeof v!=='string'){console.warn(`[i18n] missing ${l}:${k}`);v=path(dict.en,k)}if(typeof v!=='string')return'';return Object.entries(p).reduce((s,[a,b])=>s.replaceAll(`{${a}}`,String(b)),v)}
export function arr(l:LocaleCode,k:string){activeLocale=l;let v=path(dict[l],k);if(!Array.isArray(v)){console.warn(`[i18n] missing ${l}:${k}`);v=path(dict.en,k)}return Array.isArray(v)?v.map(String):[]}
export const localeName=(l:LocaleCode)=>dict[l].localeName as string;
export function hobbyName(id:string,l:LocaleCode=activeLocale){const table=names as Record<LocaleCode,Record<string,string>>;const v=table[l]?.[id]||table.en?.[id];if(!v)console.warn(`[i18n] missing hobby ${l}:${id}`);return v||''}
export type FirstProjectContent={first:string;need:string[];steps:string[]};
export function firstProject(l:LocaleCode,id:string):FirstProjectContent{activeLocale=l;const localized=firstProjects[l]?.[id],fallback=firstProjects.en?.[id];if(!localized)console.warn(`[i18n] missing first project ${l}:${id}`);return localized||fallback||{first:'',need:[],steps:[]}}
