import {StyleSheet} from 'react-native';
import {C} from './theme';

export const s = StyleSheet.create({
  root: {flex: 1, backgroundColor: C.cream},
  content: {flex: 1},
  page: {flexGrow: 1, backgroundColor: C.cream, alignItems: 'center'},
  pageInner: {width: '100%', alignSelf: 'center'},
  header: {backgroundColor: C.cream, borderBottomWidth: 1, borderBottomColor: C.line},
  headerInner: {maxWidth: 720, width: '100%', alignSelf: 'center', paddingHorizontal: 18, paddingVertical: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  wordmark: {color: C.ink, fontFamily: 'Nunito_800ExtraBold', fontSize: 24, letterSpacing: -0.5},
  settingsBtn: {minHeight: 48, paddingHorizontal: 14, borderRadius: 20, backgroundColor: C.pale, borderWidth: 1, borderColor: C.teal, justifyContent: 'center'},
  settingsBtnText: {color: C.tealInk, fontFamily: 'Nunito_700Bold', fontSize: 16},
  h1: {color: C.ink, fontFamily: 'Nunito_800ExtraBold', fontSize: 28, lineHeight: 35},
  h2: {color: C.ink, fontFamily: 'Nunito_800ExtraBold', fontSize: 22, lineHeight: 29},
  h3: {color: C.ink, fontFamily: 'Nunito_700Bold', fontSize: 18, lineHeight: 25},
  body: {color: C.ink, fontFamily: 'Nunito_400Regular', fontSize: 16, lineHeight: 23},
  small: {color: C.muted, fontFamily: 'Nunito_700Bold', fontSize: 13, letterSpacing: 0.2},
  helper: {color: C.muted, fontFamily: 'Nunito_400Regular', fontSize: 16, lineHeight: 22},
  kicker: {color: C.tealInk, fontFamily: 'Nunito_700Bold', fontSize: 12, textTransform: 'uppercase', letterSpacing: 0.9},
  card: {backgroundColor: C.white, borderWidth: 1, borderColor: C.line, borderRadius: 16, padding: 16, gap: 10},
  pale: {backgroundColor: C.pale, borderRadius: 16, padding: 16, gap: 10, borderWidth: 1, borderColor: '#C7E8F2'},
  pink: {backgroundColor: C.pink, borderRadius: 16, padding: 16, gap: 8, borderWidth: 1, borderColor: '#F3D0C8'},
  verdict: {backgroundColor: C.profitSoft, borderRadius: 18, paddingVertical: 20, paddingHorizontal: 18, borderWidth: 1.5, borderColor: C.profit, shadowColor: C.ink, shadowOffset: {width: 0, height: 2}, shadowOpacity: 0.06, shadowRadius: 8, elevation: 2},
  verdictText: {color: C.coral, fontFamily: 'Nunito_800ExtraBold', fontSize: 21, lineHeight: 28},
  resultValue: {color: C.profit, fontFamily: 'Nunito_800ExtraBold', fontSize: 46, lineHeight: 54, letterSpacing: -1},
  btn: {backgroundColor: C.coral, borderRadius: 14, minHeight: 54, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16},
  btnPressed: {backgroundColor: C.coralPressed},
  btnText: {color: C.white, fontFamily: 'Nunito_700Bold', fontSize: 17},
  outline: {backgroundColor: C.white, borderWidth: 1.5, borderColor: C.teal},
  outlinePressed: {backgroundColor: C.pale},
  outlineText: {color: C.tealInk},
  linkHit: {minHeight: 48, justifyContent: 'center', alignSelf: 'flex-start'},
  link: {color: C.tealInk, fontFamily: 'Nunito_700Bold', fontSize: 16, textDecorationLine: 'underline'},
  field: {flexGrow: 1, flexBasis: '46%', minWidth: 140, gap: 6},
  inputRow: {flexDirection: 'row', alignItems: 'center', backgroundColor: C.white, borderWidth: 1, borderColor: C.line, borderRadius: 12, paddingHorizontal: 10, minHeight: 52},
  symbol: {color: C.ink, fontFamily: 'Nunito_700Bold', fontSize: 17, marginRight: 4},
  input: {flex: 1, color: C.ink, fontFamily: 'Nunito_700Bold', fontSize: 17, paddingVertical: 8},
  grid: {flexDirection: 'row', flexWrap: 'wrap', gap: 10},
  metric: {flexGrow: 1, flexBasis: '46%', minWidth: 140, backgroundColor: C.white, borderWidth: 1, borderColor: C.line, borderRadius: 14, padding: 12, gap: 4},
  metricValue: {color: C.ink, fontFamily: 'Nunito_800ExtraBold', fontSize: 22},
  hero: {width: '100%', height: 180, borderRadius: 16, backgroundColor: C.pale},
  homeHero: {width: '100%', height: 148, borderRadius: 16, backgroundColor: C.pale, overflow: 'hidden', justifyContent: 'flex-end', padding: 18, borderWidth: 1, borderColor: '#C7E8F2'},
  heroCircleLarge: {position: 'absolute', width: 168, height: 168, borderRadius: 84, backgroundColor: C.pink, right: -30, top: -62},
  heroCircleSmall: {position: 'absolute', width: 76, height: 76, borderRadius: 38, backgroundColor: C.sky, right: 76, bottom: -30},
  heroWord: {color: C.tealInk, fontFamily: 'Nunito_800ExtraBold', fontSize: 28, letterSpacing: -0.5},
  projectHero: {width: '100%', minHeight: 126, borderRadius: 16, backgroundColor: C.pale, padding: 18, justifyContent: 'flex-end', borderWidth: 1, borderColor: '#C7E8F2', overflow: 'hidden'},
  projectHeroText: {color: C.tealInk, fontFamily: 'Nunito_800ExtraBold', fontSize: 28, lineHeight: 34},
  hobby: {flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: C.white, borderWidth: 1, borderColor: C.line, borderRadius: 14, paddingHorizontal: 10, paddingVertical: 9, minHeight: 68},
  hobbyMark: {width: 48, height: 48, borderRadius: 14, backgroundColor: C.pale, borderWidth: 1, borderColor: C.sky, alignItems: 'center', justifyContent: 'center'},
  hobbyMarkText: {color: C.tealInk, fontFamily: 'Nunito_800ExtraBold', fontSize: 22},
  arrow: {color: C.tealInk, fontFamily: 'Nunito_800ExtraBold', fontSize: 24},
  choice: {backgroundColor: C.white, borderWidth: 1.5, borderColor: C.line, borderRadius: 14, padding: 14, minHeight: 48, justifyContent: 'center'},
  choiceOn: {backgroundColor: C.pale, borderColor: C.teal},
  choiceOnText: {color: C.tealInk},
  todayCard: {backgroundColor: C.white, borderWidth: 1, borderColor: C.line, borderRadius: 16, padding: 16, gap: 10},
  todayRow: {flexDirection: 'row', alignItems: 'center', gap: 12, minHeight: 48},
  todayText: {flex: 1, color: C.ink, fontFamily: 'Nunito_700Bold', fontSize: 18, lineHeight: 24},
  bigCheck: {width: 40, height: 40, borderRadius: 20, borderWidth: 2, borderColor: C.teal, backgroundColor: C.white, alignItems: 'center', justifyContent: 'center'},
  check: {width: 28, height: 28, borderRadius: 14, borderWidth: 2, borderColor: C.teal, backgroundColor: C.white, alignItems: 'center', justifyContent: 'center'},
  checkOn: {backgroundColor: C.teal, borderColor: C.teal},
  bigCheckText: {color: C.white, fontFamily: 'Nunito_800ExtraBold', fontSize: 18},
  checkMark: {color: C.white, fontFamily: 'Nunito_800ExtraBold', fontSize: 13},
  progressTrack: {height: 8, borderRadius: 4, backgroundColor: C.line, overflow: 'hidden'},
  progressFill: {height: '100%', borderRadius: 4, backgroundColor: C.tealInk},
  cardShadow: {shadowColor: C.ink, shadowOffset: {width: 0, height: 2}, shadowOpacity: 0.06, shadowRadius: 8, elevation: 2},
  checkRow: {flexDirection: 'row', alignItems: 'flex-start', gap: 10, paddingVertical: 8, minHeight: 48},
  strike: {textDecorationLine: 'line-through', color: C.muted},
  photoRow: {flexDirection: 'row', flexWrap: 'wrap', gap: 8},
  photo: {width: 72, height: 72, borderRadius: 10, backgroundColor: C.pale},
  scenario: {gap: 8, paddingTop: 6},
  searchInput: {minHeight: 52, backgroundColor: C.white, borderWidth: 1, borderColor: C.line, borderRadius: 14, paddingHorizontal: 16, color: C.ink, fontFamily: 'Nunito_400Regular', fontSize: 17},
  note: {minHeight: 96, backgroundColor: C.white, borderWidth: 1, borderColor: C.line, borderRadius: 12, padding: 12, color: C.ink, fontFamily: 'Nunito_400Regular', fontSize: 16, textAlignVertical: 'top'},
  back: {paddingHorizontal: 18, paddingVertical: 10, borderTopWidth: 1, borderTopColor: C.line, backgroundColor: C.cream},
  shade: {flex: 1, backgroundColor: 'rgba(36,50,56,0.45)', justifyContent: 'flex-end'},
  pay: {backgroundColor: C.cream, borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingHorizontal: 20, paddingTop: 22, paddingBottom: 28, gap: 12},
  payPreview: {flexDirection: 'row', gap: 8},
  payPreviewCard: {flex: 1, minHeight: 78, backgroundColor: C.white, borderWidth: 1, borderColor: C.line, borderRadius: 14, padding: 10, justifyContent: 'space-between'},
  payPreviewMark: {width: 26, height: 4, borderRadius: 2, backgroundColor: C.teal},
  payPreviewText: {color: C.ink, fontFamily: 'Nunito_700Bold', fontSize: 13, lineHeight: 17},
  payTrust: {backgroundColor: C.pale, borderWidth: 1, borderColor: '#C7E8F2', borderRadius: 14, padding: 12},
  completionSheet: {backgroundColor: C.cream, borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingHorizontal: 20, paddingTop: 22, paddingBottom: 30, gap: 14},
  completionCard: {backgroundColor: C.profitSoft, borderWidth: 1.5, borderColor: C.profit, borderRadius: 20, padding: 18, gap: 10},
  completionValue: {color: C.profit, fontFamily: 'Nunito_800ExtraBold', fontSize: 48, lineHeight: 56, letterSpacing: -1.2},
  completionMetrics: {flexDirection: 'row', gap: 10},
  completionMetric: {flex: 1, backgroundColor: C.white, borderWidth: 1, borderColor: C.line, borderRadius: 14, padding: 12, gap: 3},
  completionBrand: {color: C.tealInk, fontFamily: 'Nunito_800ExtraBold', fontSize: 16, letterSpacing: -0.2, marginTop: 4},
  chipWrap: {flexDirection: 'row', flexWrap: 'wrap', gap: 8},
  chip: {borderWidth: 1, borderColor: C.line, backgroundColor: C.white, borderRadius: 18, paddingHorizontal: 13, paddingVertical: 9, minHeight: 48, justifyContent: 'center'},
  chipOn: {backgroundColor: C.pale, borderColor: C.teal},
  chipText: {color: C.ink, fontFamily: 'Nunito_700Bold', fontSize: 14},
  chipOnText: {color: C.tealInk},
  flowRow: {flexDirection: 'row', alignItems: 'center', backgroundColor: C.white, borderWidth: 1, borderColor: C.line, borderRadius: 16, padding: 12, gap: 8},
  flowStep: {flex: 1, gap: 3},
  flowNumber: {color: C.coral, fontFamily: 'Nunito_800ExtraBold', fontSize: 12, letterSpacing: 0.8},
  flowText: {color: C.ink, fontFamily: 'Nunito_700Bold', fontSize: 14, lineHeight: 18},
  flowRule: {width: 18, height: 1, backgroundColor: C.line},
  resultHobbyCard: {flexDirection: 'row', alignItems: 'center', gap: 14, backgroundColor: C.white, borderWidth: 1, borderColor: C.line, borderRadius: 16, padding: 12},
  resultHobbyBody: {flex: 1, gap: 4},
  historyCard: {flexDirection: 'row', alignItems: 'flex-start', gap: 14, backgroundColor: C.white, borderWidth: 1, borderColor: C.line, borderRadius: 16, padding: 12},
  historyThumb: {width: 82, height: 82, borderRadius: 14, backgroundColor: C.pale},
  historyBody: {flex: 1, gap: 7},
  historyMetrics: {gap: 2},
  historyMetricStrong: {color: C.profit, fontFamily: 'Nunito_800ExtraBold', fontSize: 22, lineHeight: 28},
  historyActions: {flexDirection: 'row', flexWrap: 'wrap', columnGap: 14, rowGap: 2},
  compareImage: {width: '100%', height: 88, borderRadius: 12, backgroundColor: C.pale},
  compareGrid: {flexDirection: 'row', gap: 10, flexWrap: 'wrap'},
  compareCard: {flexGrow: 1, flexBasis: '46%', minWidth: 220, backgroundColor: C.white, borderWidth: 1, borderColor: C.line, borderRadius: 16, padding: 12, gap: 7},
  sectionGap: {height: 8},
  payBenefits: {gap: 7, paddingVertical: 4},
  visual: {width: '100%', height: 140, borderRadius: 16, backgroundColor: C.pale},
  visualCompact: {width: 58, height: 58, borderRadius: 12, backgroundColor: C.pale},
  visualHero: {position: 'absolute', left: 0, top: 0, right: 0, bottom: 0, width: '100%', height: '100%'},
  visualOverlay: {position: 'absolute', left: 0, right: 0, bottom: 0, height: 72, backgroundColor: 'rgba(255,253,247,0.82)'},
  bottomNav: {flexDirection: 'row', backgroundColor: C.white, borderTopWidth: 1, borderTopColor: C.line, paddingHorizontal: 8, paddingTop: 4, paddingBottom: 4},
  bottomTab: {flex: 1, minHeight: 54, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4, borderRadius: 12, gap: 1},
  bottomTabOn: {backgroundColor: C.pale},
  bottomTabIcon: {color: C.muted, fontFamily: 'Nunito_800ExtraBold', fontSize: 16, lineHeight: 18},
  bottomTabIconOn: {color: C.tealInk},
  bottomTabText: {color: C.muted, fontFamily: 'Nunito_700Bold', fontSize: 13, textAlign: 'center'},
  bottomTabTextOn: {color: C.tealInk}
});
