import {StyleSheet} from 'react-native';
import {C} from './theme';

export const s = StyleSheet.create({
  root: {flex: 1, backgroundColor: C.cream},
  page: {flexGrow: 1, backgroundColor: C.cream},
  pageInner: {width: '100%', alignSelf: 'center', gap: 12},
  header: {backgroundColor: C.cream, borderBottomWidth: 1, borderBottomColor: C.line},
  headerInner: {
    maxWidth: 720,
    width: '100%',
    alignSelf: 'center',
    paddingHorizontal: 18,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between'
  },
  logo: {width: 132, height: 42},
  settingsBtn: {
    minHeight: 36,
    paddingHorizontal: 12,
    borderRadius: 18,
    backgroundColor: C.pale,
    borderWidth: 1,
    borderColor: C.teal,
    justifyContent: 'center'
  },
  settingsBtnText: {color: C.tealInk, fontFamily: 'Nunito_700Bold', fontSize: 14},
  h1: {color: C.ink, fontFamily: 'Nunito_800ExtraBold', fontSize: 28, lineHeight: 34},
  h2: {color: C.ink, fontFamily: 'Nunito_800ExtraBold', fontSize: 22, lineHeight: 28},
  h3: {color: C.ink, fontFamily: 'Nunito_700Bold', fontSize: 18, lineHeight: 24},
  body: {color: C.ink, fontFamily: 'Nunito_400Regular', fontSize: 17, lineHeight: 24},
  small: {color: C.muted, fontFamily: 'Nunito_700Bold', fontSize: 13, letterSpacing: 0.2},
  helper: {color: C.muted, fontFamily: 'Nunito_400Regular', fontSize: 14, lineHeight: 20},
  kicker: {color: C.tealInk, fontFamily: 'Nunito_700Bold', fontSize: 13, textTransform: 'uppercase', letterSpacing: 0.6},
  card: {backgroundColor: C.white, borderWidth: 1, borderColor: C.line, borderRadius: 16, padding: 14, gap: 8},
  pale: {backgroundColor: C.pale, borderRadius: 16, padding: 14, gap: 8, borderWidth: 1, borderColor: '#C7E8F2'},
  pink: {backgroundColor: C.pink, borderRadius: 16, padding: 14, gap: 6, borderWidth: 1, borderColor: '#F3D0C8'},
  verdict: {backgroundColor: C.pink, borderRadius: 16, paddingVertical: 14, paddingHorizontal: 14, borderWidth: 1, borderColor: '#F3D0C8'},
  verdictText: {color: C.coral, fontFamily: 'Nunito_800ExtraBold', fontSize: 26, lineHeight: 32},
  btn: {backgroundColor: C.coral, borderRadius: 14, minHeight: 48, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16},
  btnPressed: {backgroundColor: C.coralPressed},
  btnText: {color: C.white, fontFamily: 'Nunito_700Bold', fontSize: 17},
  outline: {backgroundColor: C.white, borderWidth: 1.5, borderColor: C.teal},
  outlinePressed: {backgroundColor: C.pale},
  outlineText: {color: C.tealInk},
  linkHit: {paddingVertical: 4},
  link: {color: C.tealInk, fontFamily: 'Nunito_700Bold', fontSize: 16, textDecorationLine: 'underline'},
  field: {flexGrow: 1, flexBasis: '46%', gap: 6},
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 12,
    paddingHorizontal: 10,
    minHeight: 46
  },
  symbol: {color: C.ink, fontFamily: 'Nunito_700Bold', fontSize: 17, marginRight: 4},
  input: {flex: 1, color: C.ink, fontFamily: 'Nunito_700Bold', fontSize: 17, paddingVertical: 8},
  grid: {flexDirection: 'row', flexWrap: 'wrap', gap: 10},
  metric: {
    flexGrow: 1,
    flexBasis: '46%',
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 14,
    padding: 12,
    gap: 4
  },
  metricValue: {color: C.ink, fontFamily: 'Nunito_800ExtraBold', fontSize: 22},
  hero: {width: '100%', height: 168, borderRadius: 16, backgroundColor: C.pale},
  hobby: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 14,
    padding: 10
  },
  thumb: {width: 56, height: 56, borderRadius: 10, backgroundColor: C.pale},
  arrow: {color: C.tealInk, fontFamily: 'Nunito_800ExtraBold', fontSize: 24},
  choice: {backgroundColor: C.white, borderWidth: 1.5, borderColor: C.line, borderRadius: 14, padding: 14},
  choiceOn: {backgroundColor: C.pale, borderColor: C.teal},
  choiceOnText: {color: C.tealInk},
  todayCard: {backgroundColor: C.white, borderWidth: 1, borderColor: C.line, borderRadius: 16, padding: 14, gap: 10},
  todayRow: {flexDirection: 'row', alignItems: 'center', gap: 12},
  todayText: {flex: 1, color: C.ink, fontFamily: 'Nunito_700Bold', fontSize: 18, lineHeight: 24},
  bigCheck: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: C.teal,
    backgroundColor: C.white,
    alignItems: 'center',
    justifyContent: 'center'
  },
  check: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: C.teal,
    backgroundColor: C.white,
    alignItems: 'center',
    justifyContent: 'center'
  },
  checkOn: {backgroundColor: C.teal, borderColor: C.teal},
  bigCheckText: {color: C.white, fontFamily: 'Nunito_800ExtraBold', fontSize: 18},
  checkMark: {color: C.white, fontFamily: 'Nunito_800ExtraBold', fontSize: 13},
  checkRow: {flexDirection: 'row', alignItems: 'flex-start', gap: 10, paddingVertical: 4},
  strike: {textDecorationLine: 'line-through', color: C.muted},
  photoRow: {flexDirection: 'row', flexWrap: 'wrap', gap: 8},
  photo: {width: 64, height: 64, borderRadius: 10, backgroundColor: C.pale},
  scenario: {gap: 8, paddingTop: 6},
  note: {
    minHeight: 88,
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 12,
    padding: 12,
    color: C.ink,
    fontFamily: 'Nunito_400Regular',
    fontSize: 16,
    textAlignVertical: 'top'
  },
  back: {paddingHorizontal: 18, paddingVertical: 8, borderTopWidth: 1, borderTopColor: C.line, backgroundColor: C.cream},
  shade: {flex: 1, backgroundColor: 'rgba(36,50,56,0.45)', justifyContent: 'flex-end'},
  pay: {backgroundColor: C.cream, borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 20, gap: 12},
  chipRow: {gap: 8, paddingVertical: 4},
  chipWrap: {flexDirection: 'row', flexWrap: 'wrap', gap: 8},
  chip: {borderWidth: 1, borderColor: C.line, backgroundColor: C.white, borderRadius: 16, paddingHorizontal: 12, paddingVertical: 8},
  chipOn: {backgroundColor: C.pale, borderColor: C.teal},
  chipText: {color: C.ink, fontFamily: 'Nunito_700Bold', fontSize: 14},
  chipOnText: {color: C.tealInk},
  compareGrid: {flexDirection: 'row', gap: 10, flexWrap: 'wrap'},
  compareCard: {flexGrow: 1, flexBasis: '46%', backgroundColor: C.white, borderWidth: 1, borderColor: C.line, borderRadius: 14, padding: 12, gap: 6}
});
